In [ ]:
#Name: Advik Sharma
#Class Roll No.: CSC/20/32
#University Roll No.: 20059570024

#PROGRAM 3: Matrices

In [17]:
# (a) Perform basic operations on matrices:

# (i) addition of 2 matrices
import numpy as np
arr1 = np.array(np.random.randn(9), dtype='int32').reshape(3,3)
arr2 = np.array(np.random.randint(1,25,(3,3)))
print("The two matrices are as follows: \n", arr1, "and\n", arr2)

The two matrices are as follows: 
 [[ 0 -1  0]
 [ 2  0  0]
 [ 0 -1  0]] and
 [[19 16  1]
 [19 13 19]
 [12 22 18]]


In [19]:
addition = arr1 + arr2
print("Addition of the two matrices: \n", addition)

Addition of the two matrices: 
 [[19 15  1]
 [21 13 19]
 [12 21 18]]


In [20]:
#  (ii) subtraction of 2 matrices
subtraction = arr2 - arr1
print("Subtraction of the two matrices: \n", subtraction)

Subtraction of the two matrices: 
 [[19 17  1]
 [17 13 19]
 [12 23 18]]


In [21]:
# (iii) multiplication of 2 matrices
multiplication = arr1 * arr2
print("Multiplication of the two matrices: \n", multiplication)

Multiplication of the two matrices: 
 [[  0 -16   0]
 [ 38   0   0]
 [  0 -22   0]]


In [28]:
#  (iv) find the transpose of a matrix
transpose = arr2.T
print("Transpose of the matrix: \n", arr2, " is\n\n", transpose)

Transpose of the matrix: 
 [[19 16  1]
 [19 13 19]
 [12 22 18]]  is

 [[19 19 12]
 [16 13 22]
 [ 1 19 18]]


In [48]:
# (b) Display specific rows or columns of a matrix.
print("First row of arr1 = ", arr1[0])
print("Second row of arr1 = ", arr1[1])
print("Third row of arr1 = ", arr1[2])
print("\n")
print("First column of arr2 = ", arr2[:, 0])
print("Second column of arr2 = ", arr2[:, 1])
print("Third column of arr2 = ", arr2[:, 2])

First row of arr1 =  [ 0 -1  0]
Second row of arr1 =  [2 0 0]
Third row of arr1 =  [ 0 -1  0]


First column of arr2 =  [19 19 12]
Second column of arr2 =  [16 13 22]
Third column of arr2 =  [ 1 19 18]
