In [1]:
#Program 1- Arrays and matrices

#(a) Create arrays with specific values:

# (i) array of all ones
import numpy as np
arr_ones = np.ones(6)
print("Array of all ones(size=6): ", arr_ones)

Array of all ones(size=6):  [1. 1. 1. 1. 1. 1.]


In [2]:
# (ii) array of all zeros
arr_zeros = np.zeros(6)
print("Array of all zeros(size=6): ", arr_zeros)

Array of all zeros(size=6):  [0. 0. 0. 0. 0. 0.]


In [7]:
# (iii) array with random values within a range
arr_random = np.random.randint(1,100, (4,5))        #randint function of random package generates random integers
print("A 4x5 Array with random values within the range 1-100: \n", arr_random)

A 4x5 Array with random values within the range 1-100: 
 [[45 32 40 90 68]
 [37 95 11 52 12]
 [92 79 76 73 41]
 [69 59 63 21 91]]


In [10]:
# (iv) a diagonal matrix
v = [1,2,3,4]
print("Diagonal matrix: \n", np.diag(v))           #np.diag() takes a list of values and arranges them as a diagonal in a matrix

Diagonal matrix: 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [59]:
# (b) Perform other matrix operations:
arr = np.array(np.random.randn(12)).reshape(4,3)
arr

array([[ 0.04998671,  0.63402517, -0.62105265],
       [-1.47940099,  0.48424899, -0.82886212],
       [ 0.87245699,  2.06817737,  0.30184584],
       [-0.46942011, -0.24547182,  1.15929182]])

In [60]:
# (i) convert matrix data to absolute values
print("Array of absolute values: \n", np.absolute(arr))

Array of absolute values: 
 [[0.04998671 0.63402517 0.62105265]
 [1.47940099 0.48424899 0.82886212]
 [0.87245699 2.06817737 0.30184584]
 [0.46942011 0.24547182 1.15929182]]


In [61]:
# (ii) take the negative of matrix values
print("Negative of matrix values: \n", arr * -1 )

Negative of matrix values: 
 [[-0.04998671 -0.63402517  0.62105265]
 [ 1.47940099 -0.48424899  0.82886212]
 [-0.87245699 -2.06817737 -0.30184584]
 [ 0.46942011  0.24547182 -1.15929182]]


In [70]:
# (iii) add rows & columns to a matrix
column = np.array([[0],[1],[2],[3]])                  #adding a column
arr_col = np.append(arr, column, axis=1)
print("New array with added column: \n", arr_col)

New array with added column: 
 [[ 0.04998671  0.63402517 -0.62105265  0.        ]
 [-1.47940099  0.48424899 -0.82886212  1.        ]
 [ 0.87245699  2.06817737  0.30184584  2.        ]
 [-0.46942011 -0.24547182  1.15929182  3.        ]]


In [69]:
row = np.array([[0,1,2]])                             #adding a row
arr_row = np.append(arr, row, axis=0)       
print("New array with added row: \n", arr_row)

New array with added row: 
 [[ 0.04998671  0.63402517 -0.62105265]
 [-1.47940099  0.48424899 -0.82886212]
 [ 0.87245699  2.06817737  0.30184584]
 [-0.46942011 -0.24547182  1.15929182]
 [ 0.          1.          2.        ]]


In [83]:
# (iv) remove rows & columns from a matrix
print("Removing second row: \n", np.delete(arr, 1, 0))                             #deleting second row

Removing second row: 
 [[ 0.04998671  0.63402517 -0.62105265]
 [ 0.87245699  2.06817737  0.30184584]
 [-0.46942011 -0.24547182  1.15929182]]


In [84]:
print("Removing first column: \n", np.delete(arr, 0, 1))                           #deleting first column

Removing first column: 
 [[ 0.63402517 -0.62105265]
 [ 0.48424899 -0.82886212]
 [ 2.06817737  0.30184584]
 [-0.24547182  1.15929182]]


In [77]:
# (v) find the maximum and  minimum values in a matrix or in a row/column
arr.min(axis=1)                                  #minimum value in each row

array([-0.62105265, -1.47940099,  0.30184584, -0.46942011])

In [79]:
arr.max(axis=0)                                  #maximum value in each column

array([0.87245699, 2.06817737, 1.15929182])

In [80]:
print("Maximum value in the matrix= ", arr.max())        #max value of matrix
print("Minimum value in the matrix= ", arr.min())        #min value of matrix

Maximum value in the matrix=  2.068177372426769
Minimum value in the matrix=  -1.4794009863808495


In [82]:
# (vi) find the sum of some/all elements in a matrix
x = arr.sum(axis=1)
y = arr.sum(axis=0)
z = arr.sum()
print("Sum of elements in each row: ", x)
print("Sum of elements in each column: ", y)
print("Sum of all elements: ", z)

Sum of elements in each row:  [ 0.06295922 -1.82401413  3.24248021  0.44439989]
Sum of elements in each column:  [-1.0263774   2.94097971  0.01122289]
Sum of all elements:  1.9258251922288072
